### ISSUE TITLE
Need help finishing the Wii Number validation

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/wiino#1]
I think I've done most of the work to unscramble a Wii Number, but I'm not quite there yet. The final step isn't giving back the right number. Can someone please help?

**Comment by KcrPL** [comment]
Sure, ~~is it made in batch?~~

**Comment by Artuto** [comment]
If it was it probably wouldnt even boot

**Comment by InternalLoss** [comment]
Isn't this now complete as of last night?

**Comment by larsenv** [comment]
Yes
